// AUTH
export const REMEMBER_USER = 'REMEMBER_USER';

// NOTIFICATION STATUS
export const N_PENDING = 'PENDING';
export const N_COMPLETED = 'COMPLETED';
export const N_ERROR = 'PENDING';

// AUTHENTICATION TOKEN
export const TOKEN_KEY = 'TOKEN_KEY';
export const TOKEN_TTL = 'TOKEN_TTL';

// PASSWORD CHANGE TOKEN
export const TOKEN_KEY_TO_CHANGE_PASS = 'TOKEN_KEY_TO_CHANGE_PASS';
